# configuration file for dotnet-releaser
[msbuild]
project = "GottaManagePlus.sln"
configuration = "Release"
[github]
user = "PixelGuy123"
repo = "GottaManagePlus"
[msbuild.properties]
PublishTrimmed = false
PublishSingleFile = false
SelfContained = true
PublishReadyToRun = true 
CopyOutputSymbolsToPublishDirectory = false
SkipCopyingSymbolsToOutputDirectory = true 
# Create zip files only for Windows platforms
[[pack]]
rid = ["win-x64"]
kinds = ["zip"]
# Default targets for Linux/Ubuntu Debian compatible distro with debian and tar packages
[[pack]]
rid = ["linux-x64"]
kinds = ["deb", "tar"]
# Pack to remove rids not needed
[[pack]]
rid = ["osx-x64", "osx-arm64", "linux-arm64", "win-arm64"]
publish=false
